### ISSUE TITLE
There are more subjects in total after matching

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#3]
In the use case 3 in DLBCL_use_case example, it was assumed to have 515 patients in total for three arms. However, after matching, it became 1030 patients in total and the original 515 patients were duplicated. I found the problem was related to "rbind" function used in the statement "match.all <- as.matrix(rbind(dt.match_ext, dt_int) %>% select(-"int"))" in "m_cov" function.

**Comment by JiawenZhuxm** [comment]
Not all patients got a matched pair, so we only have 435 patients (220 from the trial, 212 from external control). The dataset have 620 rows (ssC = 100, ssE = 120, ssExt = 400). Package MatchIt was used. I would say if there is an error, let's fix it since people may use it. But it seems by running the example code, the duplication issue is no longer there?

**Comment by pathwayrf** [comment]
PSM should be supported. The duplication issue as pointed out earlier should be fixed if it's not already been.

**Comment by JiawenZhuxm** [comment]
The result I got have less than 620 rows, i.e. 433 rows. 
List of 1
 $ : num [1:433, 1:6] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:433] "4" "7" "11" "13" ...
  .. ..$ : chr [1:6] "driftHR" "HR" "ext" "trt" ...

The returned message:
"187 patients from the external arm are excluded. 7 patients from the internal trial are excluded.
After matching, we have 433 patients in total."
